// Endspiel NNUE Trainer
//
// Trains a HalfKP 704×32→768×2→1 SCReLU network using the Bullet trainer.
// The output `quantised.bin` is directly compatible with the engine's
// `crates/chess-nnue/nets/default.nnue` format.
//
// Usage:
//   cd train
//   cargo run --release -- --data ../data.txt [OPTIONS]
//
// Prerequisites:
//   - CUDA toolkit installed (or use --features cpu --no-default-features)
//   - Training data generated by chess-datagen in "FEN | score | result" format

#[allow(deprecated)]
use bullet_lib::{
    game::inputs::ChessBucketsMergedKingsMirrored,
    nn::optimiser::AdamW,
    trainer::{
        save::SavedFormat,
        schedule::{TrainingSchedule, TrainingSteps, lr, wdl},
        settings::LocalSettings,
    },
    value::{ValueTrainerBuilder, loader::DirectSequentialDataLoader},
};
use bullet_compiler::tensor::TValue;

const HIDDEN_SIZE: usize = 768;
const SCALE: i32 = 400;
const INPUT_SIZE: usize = 704 * 32; // HalfKP: 704 features × 32 king-square buckets

const QA: i16 = 127;
const QB: i16 = 64;

const NET_FILE_SIZE: usize =
    INPUT_SIZE * HIDDEN_SIZE * 2   // l0w (i16)
    + HIDDEN_SIZE * 2              // l0b (i16)
    + HIDDEN_SIZE * 2              // l1w (i8)
    + 2;                           // l1b (i16)

fn main() {
    let args: Vec<String> = std::env::args().collect();

    let mut data_path = String::from("../data.bin");
    let mut superbatches: usize = 60;
    let mut superbatches_explicit = false;
    let mut start_superbatch: usize = 1;
    let mut resume_path: Option<String> = None;
    let mut save_rate: usize = 10;
    let mut lr_start: f32 = 0.001;
    let mut lr_explicit = false;
    let mut wdl_proportion: f32 = 0.75;
    let mut wdl_explicit = false;
    let mut init_net_path: Option<String> = None;
    let mut finetune = false;
    let mut net_id = String::from("endspiel");
    let mut output_dir = String::from("checkpoints");
    let mut bps_override: Option<usize> = None;
    let mut epochs: usize = 1;
    let mut epochs_explicit = false;

    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--data" => {
                i += 1;
                data_path = args[i].clone();
            }
            "--superbatches" => {
                i += 1;
                superbatches = args[i].parse().expect("invalid --superbatches");
                superbatches_explicit = true;
            }
            "--start" => {
                i += 1;
                start_superbatch = args[i].parse().expect("invalid --start");
            }
            "--resume" => {
                i += 1;
                resume_path = Some(args[i].clone());
            }
            "--save-rate" => {
                i += 1;
                save_rate = args[i].parse().expect("invalid --save-rate");
            }
            "--lr" => {
                i += 1;
                lr_start = args[i].parse().expect("invalid --lr");
                lr_explicit = true;
            }
            "--wdl" => {
                i += 1;
                wdl_proportion = args[i].parse().expect("invalid --wdl");
                wdl_explicit = true;
            }
            "--init-net" => {
                i += 1;
                init_net_path = Some(args[i].clone());
            }
            "--finetune" => {
                finetune = true;
            }
            "--name" => {
                i += 1;
                net_id = args[i].clone();
            }
            "--output" => {
                i += 1;
                output_dir = args[i].clone();
            }
            "--epochs" => {
                i += 1;
                epochs = args[i].parse().expect("invalid --epochs");
                epochs_explicit = true;
            }
            "--bps" => {
                i += 1;
                bps_override = Some(args[i].parse().expect("invalid --bps"));
            }
            "--help" | "-h" => {
                eprintln!("Endspiel NNUE Trainer (HalfKP 704×32→{HIDDEN_SIZE}×2→1 SCReLU)");
                eprintln!();
                eprintln!("Usage: train [OPTIONS]");
                eprintln!();
                eprintln!("Options:");
                eprintln!("  --data PATH         Training data file in binary ChessBoard format (default: ../data.bin)");
                eprintln!("  --superbatches N    Total superbatches to train (default: 60)");
                eprintln!("  --start N           Start superbatch, for resuming (default: 1)");
                eprintln!("  --resume DIR        Checkpoint directory to resume from (e.g. checkpoints/endspiel-200)");
                eprintln!("  --save-rate N       Save checkpoint every N superbatches (default: 10)");
                eprintln!("  --lr F              Initial learning rate (default: 0.001)");
                eprintln!("  --wdl F             WDL proportion, 0.0-1.0 (default: 0.75)");
                eprintln!("  --init-net PATH     Warm-start from an existing quantised .nnue/.bin net");
                eprintln!("  --finetune          Warm-start preset: lr=0.00001, superbatches=8, wdl=0.5, bps=8 (requires --init-net)");
                eprintln!("  --name ID           Network name for checkpoints (default: endspiel)");
                eprintln!("  --output DIR        Checkpoint output directory (default: checkpoints)");
                eprintln!("  --epochs N          Passes through the dataset (default: 1)
  --bps N             Batches per superbatch (overrides auto-computed value)");
                std::process::exit(0);
            }
            other => {
                eprintln!("Unknown argument: {other}");
                std::process::exit(1);
            }
        }
        i += 1;
    }

    if finetune {
        if resume_path.is_some() {
            panic!("--finetune cannot be used with --resume; use one workflow at a time");
        }
        if init_net_path.is_none() {
            panic!("--finetune requires --init-net PATH");
        }

        if !lr_explicit {
            lr_start = 0.00001;
        }
        if !epochs_explicit {
            epochs = 1;
        }
        if !superbatches_explicit {
            superbatches = 8;
        }
        if !wdl_explicit {
            wdl_proportion = 0.5;
        }
        if bps_override.is_none() {
            bps_override = Some(8);
        }

        eprintln!(
            "Fine-tune preset active: lr={lr_start}, epochs={epochs}, superbatches={superbatches}, wdl={wdl_proportion}, bps={}"
            , bps_override.unwrap_or(0)
        );
    }

    let lr_end = lr_start * 0.3f32.powi(5);

    const BYTES_PER_POSITION: u64 = 32;
    const BATCH_SIZE: usize = 16_384;

    let num_positions = std::fs::metadata(&data_path)
        .unwrap_or_else(|e| panic!("cannot stat data file '{data_path}': {e}"))
        .len()
        / BYTES_PER_POSITION;
    let batches_per_superbatch = bps_override.unwrap_or_else(|| {
        let bps = num_positions as usize * epochs / (superbatches * BATCH_SIZE);
        if bps == 0 {
            panic!(
                "dataset too small: {num_positions} positions × {epochs} epochs / ({superbatches} superbatches × {BATCH_SIZE} batch) = 0 batches/superbatch. \
                Reduce --superbatches, increase --epochs, or provide more data."
            );
        }
        bps
    });

    let total_positions = num_positions as usize * epochs;
    eprintln!("Dataset: {data_path}  ({num_positions} positions, {epochs} epoch(s) = {total_positions} total)");

    // Identity layout: each of the 32 half-board king squares is its own bucket.
    // Combined with horizontal mirroring this gives full per-square king sensitivity (HalfKP).
    const BUCKET_LAYOUT: [usize; 32] = [
         0,  1,  2,  3, // rank 0
         4,  5,  6,  7, // rank 1
         8,  9, 10, 11, // rank 2
        12, 13, 14, 15, // rank 3
        16, 17, 18, 19, // rank 4
        20, 21, 22, 23, // rank 5
        24, 25, 26, 27, // rank 6
        28, 29, 30, 31, // rank 7
    ];

    #[allow(deprecated)]
    let mut trainer = ValueTrainerBuilder::default()
        .dual_perspective()
        .optimiser(AdamW)
        .inputs(ChessBucketsMergedKingsMirrored::new(BUCKET_LAYOUT))
        .save_format(&[
            SavedFormat::id("l0w").round().quantise::<i16>(QA),
            SavedFormat::id("l0b").round().quantise::<i16>(QA),
            SavedFormat::id("l1w").round().quantise::<i8>(QB),
            SavedFormat::id("l1b").round().quantise::<i16>(QA * QB),
        ])
        .loss_fn(|output, target| output.sigmoid().squared_error(target))
        .build(|builder, stm_inputs, ntm_inputs| {
            let l0 = builder.new_affine("l0", 704 * 32, HIDDEN_SIZE);
            let l1 = builder.new_affine("l1", 2 * HIDDEN_SIZE, 1);

            let stm_hidden = l0.forward(stm_inputs).screlu();
            let ntm_hidden = l0.forward(ntm_inputs).screlu();
            let hidden_layer = stm_hidden.concat(ntm_hidden);
            l1.forward(hidden_layer)
        });

    let schedule = TrainingSchedule {
        net_id,
        eval_scale: SCALE as f32,
        steps: TrainingSteps {
            batch_size: BATCH_SIZE,
            batches_per_superbatch,
            start_superbatch,
            end_superbatch: superbatches,
        },
        wdl_scheduler: wdl::ConstantWDL { value: wdl_proportion },
        lr_scheduler: lr::CosineDecayLR {
            initial_lr: lr_start,
            final_lr: lr_end,
            final_superbatch: superbatches,
        },
        save_rate,
    };

    let settings = LocalSettings {
        threads: 4,
        test_set: None,
        output_directory: &output_dir,
        batch_queue_size: 64,
    };

    if let Some(path) = &resume_path {
        eprintln!("Resuming from checkpoint: {path}");
        let optimiser_state_path = format!("{path}/optimiser_state");
        trainer
            .optimiser
            .load_from_checkpoint(&optimiser_state_path)
            .unwrap_or_else(|e| panic!("resume failed loading checkpoint '{path}': {e:?}"));
    } else if let Some(path) = &init_net_path {
        eprintln!("Warm-starting from net: {path}");
        let bytes = std::fs::read(path)
            .unwrap_or_else(|e| panic!("failed to read warm-start net '{path}': {e}"));
        if bytes.len() < NET_FILE_SIZE {
            panic!(
                "warm-start net '{path}' is too small: {} bytes (need at least {NET_FILE_SIZE})",
                bytes.len()
            );
        }

        let mut offset = 0usize;
        let read_i16 = |data: &[u8], offset: &mut usize| -> i16 {
            let v = i16::from_le_bytes([data[*offset], data[*offset + 1]]);
            *offset += 2;
            v
        };

        let mut l0w = vec![0.0f32; INPUT_SIZE * HIDDEN_SIZE];
        for x in &mut l0w {
            *x = read_i16(&bytes, &mut offset) as f32 / QA as f32;
        }

        let mut l0b = vec![0.0f32; HIDDEN_SIZE];
        for x in &mut l0b {
            *x = read_i16(&bytes, &mut offset) as f32 / QA as f32;
        }

        let mut l1w = vec![0.0f32; HIDDEN_SIZE * 2];
        for x in &mut l1w {
            *x = bytes[offset] as i8 as f32 / QB as f32;
            offset += 1;
        }

        let mut l1b = vec![0.0f32; 1];
        l1b[0] = read_i16(&bytes, &mut offset) as f32 / (QA as f32 * QB as f32);

        for (id, vals) in [("l0w", l0w), ("l0b", l0b), ("l1w", l1w), ("l1b", l1b)] {
            let ok = trainer.optimiser.model.set_weights(id, &TValue::F32(vals));
            if !ok {
                panic!("warm-start failed: missing weight id '{id}'");
            }
        }
    }

    let dataloader = DirectSequentialDataLoader::new(&[&data_path]);

    trainer.run(&schedule, &settings, &dataloader);
}
